# Setup
title:        duanzx's blog
tagline:      思而不学，犹豫不决
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author:
  name:       duanzx
  url:        https://duanzx.github.io

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown